### ISSUE TITLE
Confluence pages should include table of contents

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/happi-to-confluence#10]
There is probably a good reason why there is no table of contents on each page, but if there is not please include one to enhance navigation.

**Comment by klauer** [comment]
My only reason was that keeping the device description at the very top seemed useful from typhos - so you don't have to scroll down to see it.

If others agree that table of contents would be preferable, I am completely open to that.

(@ZLLentz? @silkenelson?)

**Comment by ZLLentz** [comment]
We can do a collapsed/expandable section containing the table of contents, right? In order to try to settle on a happy medium. I did like immediately seeing the device name and some context text when I opened the page. Maybe something e.g.
```
Big-device-name-title
---------------------
Short description

> collapsed table of contents

next section header
-------------------
stuff stuff stuff
```

**Comment by slacAWallace** [comment]
It looks like the ToC is on the notes page. Could it be on the root page? It doesn't have to be at the very tippy top.
