### ISSUE TITLE
Consider some form of automated per-device screenshot inclusion

### ISSUE THREAD

**Issue by klauer** [pcdshub/happi-to-confluence#18]
`typhos --screenshot` can be used in this scenario

The frequency will never be enough to be actually *useful* for control system values
Daily/weekly updates could be sufficient to help with UI system validation/regression checking/other fancy word here

**Comment by klauer** [comment]
I think this would be useful for _us_ but not necessarily for end users. I'd vote to close it
@ZLLentz @tangkong ?

**Comment by tangkong** [comment]
I think I agree.  Maybe the screenshots go somewhere else.  Scrolling through them in confluence might be a bit overwhelming

**Comment by ZLLentz** [comment]
I think I agree too
